# Generated by Django 4.2.11 on 2024-04-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
                ('officeType', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('serial', models.CharField(max_length=255)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('ram', models.CharField(blank=True, max_length=255, null=True)),
                ('deviceType', models.CharField(blank=True, max_length=255, null=True)),
                ('sectorCode', models.CharField(blank=True, max_length=255, null=True)),
                ('numOfWindows', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevicesModuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('deviceType', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OfficesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=255)),
                ('sectorCode', models.IntegerField()),
                ('office', models.CharField(max_length=255)),
                ('officeType', models.CharField(max_length=255)),
                ('numOfWindows', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(max_length=255)),
                ('sectorCode', models.IntegerField()),
                ('sector', models.CharField(max_length=255)),
            ],
        ),
    ]
